/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_proyect;

/**
 *
 * @author Christian
 */
public class Calculadora_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora_JFrame
     */
    double num, ans;
    int Calculation;

    public void arithemtic_operation() {
        switch (Calculation) {
            case 1: // Suma
                ans = num + Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;

            case 2: // Resta
                ans = num - Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;

            case 3: // multiplicacion
                ans = num * Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;

            case 4: //Division
                ans = num / Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(ans));
                break;
        }
    }

    public Calculadora_JFrame() {
        initComponents();

        jRadioButton1.setEnabled(false); //Enciende el boton

    }

    public void enable() {

        jRadioButton1.setEnabled(false);  //On encendido
        jRadioButton2.setEnabled(true); //OFF apagado

        jTextField1.setEnabled(true);

        Boton_0.setEnabled(true);
        Boton_1.setEnabled(true);
        Boton_2.setEnabled(true);
        Boton_3.setEnabled(true);
        Boton_4.setEnabled(true);
        Boton_5.setEnabled(true);
        Boton_6.setEnabled(true);
        Boton_7.setEnabled(true);
        Boton_8.setEnabled(true);
        Boton_9.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Suma.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Borrar.setEnabled(true);
        Boton_Punto.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Borrar.setEnabled(true);
        Boton_nose.setEnabled(true);
    }

    public void disable() {

        jRadioButton1.setEnabled(true);  //On encendido
        jRadioButton2.setEnabled(false); //OFF apagado

        jTextField1.setEnabled(false);

        Boton_0.setEnabled(false);
        Boton_1.setEnabled(false);
        Boton_2.setEnabled(false);
        Boton_3.setEnabled(false);
        Boton_4.setEnabled(false);
        Boton_5.setEnabled(false);
        Boton_6.setEnabled(false);
        Boton_7.setEnabled(false);
        Boton_8.setEnabled(false);
        Boton_9.setEnabled(false);
        Boton_Multiplicacion.setEnabled(false);
        Boton_Division.setEnabled(false);
        Boton_Suma.setEnabled(false);
        Boton_Resta.setEnabled(false);
        Boton_Borrar.setEnabled(false);
        Boton_Punto.setEnabled(false);
        Boton_Igual.setEnabled(false);
        Boton_Borrar.setEnabled(false);
        Boton_nose.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Boton_nose = new javax.swing.JButton();
        Boton_Borrar = new javax.swing.JButton();
        Boton_Suma = new javax.swing.JButton();
        Boton_7 = new javax.swing.JButton();
        Boton_8 = new javax.swing.JButton();
        Boton_9 = new javax.swing.JButton();
        Boton_Resta = new javax.swing.JButton();
        Boton_Multiplicacion = new javax.swing.JButton();
        Boton_6 = new javax.swing.JButton();
        Boton_5 = new javax.swing.JButton();
        Boton_4 = new javax.swing.JButton();
        Boton_1 = new javax.swing.JButton();
        Boton_2 = new javax.swing.JButton();
        Boton_3 = new javax.swing.JButton();
        Boton_Division = new javax.swing.JButton();
        Boton_0 = new javax.swing.JButton();
        Boton_Punto = new javax.swing.JButton();
        Boton_Igual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setLocation(new java.awt.Point(500, 225));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 225));
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        Boton_nose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Boton_nose.setText("<--");
        Boton_nose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_noseActionPerformed(evt);
            }
        });

        Boton_Borrar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_Borrar.setText("C");
        Boton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BorrarActionPerformed(evt);
            }
        });

        Boton_Suma.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_Suma.setText("+");
        Boton_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SumaActionPerformed(evt);
            }
        });

        Boton_7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_7.setText("7");
        Boton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_7ActionPerformed(evt);
            }
        });

        Boton_8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_8.setText("8");
        Boton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_8ActionPerformed(evt);
            }
        });

        Boton_9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_9.setText("9");
        Boton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_9ActionPerformed(evt);
            }
        });

        Boton_Resta.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_Resta.setText("-");
        Boton_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RestaActionPerformed(evt);
            }
        });

        Boton_Multiplicacion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_Multiplicacion.setText("*");
        Boton_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_MultiplicacionActionPerformed(evt);
            }
        });

        Boton_6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_6.setText("6");
        Boton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_6ActionPerformed(evt);
            }
        });

        Boton_5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_5.setText("5");
        Boton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_5ActionPerformed(evt);
            }
        });

        Boton_4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_4.setText("4");
        Boton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_4ActionPerformed(evt);
            }
        });

        Boton_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_1.setText("1");
        Boton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_1ActionPerformed(evt);
            }
        });

        Boton_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_2.setText("2");
        Boton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_2ActionPerformed(evt);
            }
        });

        Boton_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_3.setText("3");
        Boton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_3ActionPerformed(evt);
            }
        });

        Boton_Division.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_Division.setText("/");
        Boton_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DivisionActionPerformed(evt);
            }
        });

        Boton_0.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_0.setText("0");
        Boton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_0ActionPerformed(evt);
            }
        });

        Boton_Punto.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_Punto.setText(".");
        Boton_Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PuntoActionPerformed(evt);
            }
        });

        Boton_Igual.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Boton_Igual.setText("=");
        Boton_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_IgualActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addGap(30, 30, 30)
                        .addComponent(Boton_nose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Boton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Boton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Boton_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Boton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Boton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Boton_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Boton_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Boton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_nose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_6ActionPerformed
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_Boton_6ActionPerformed

    private void Boton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_5ActionPerformed
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_Boton_5ActionPerformed

    private void Boton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_4ActionPerformed
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_Boton_4ActionPerformed

    private void Boton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_1ActionPerformed
        jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_Boton_1ActionPerformed

    private void Boton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_2ActionPerformed
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_Boton_2ActionPerformed

    private void Boton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_3ActionPerformed
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_Boton_3ActionPerformed

    private void Boton_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DivisionActionPerformed
        num = Double.parseDouble(jTextField1.getText());
        Calculation = 4;
        jTextField1.setText("");
        jLabel1.setText(num + "/");
    }//GEN-LAST:event_Boton_DivisionActionPerformed

    private void Boton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_0ActionPerformed
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_Boton_0ActionPerformed

    private void Boton_PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PuntoActionPerformed
        jTextField1.setText(jTextField1.getText() + ".");
    }//GEN-LAST:event_Boton_PuntoActionPerformed

    private void Boton_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_IgualActionPerformed
        arithemtic_operation();
        jLabel1.setText("");
    }//GEN-LAST:event_Boton_IgualActionPerformed

    private void Boton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_7ActionPerformed
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_Boton_7ActionPerformed

    private void Boton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_8ActionPerformed
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_Boton_8ActionPerformed

    private void Boton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_9ActionPerformed
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_Boton_9ActionPerformed

    private void Boton_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RestaActionPerformed
        num = Double.parseDouble(jTextField1.getText());
        Calculation = 2;
        jTextField1.setText("");
        jLabel1.setText(num + "-");
    }//GEN-LAST:event_Boton_RestaActionPerformed

    private void Boton_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_MultiplicacionActionPerformed
        num = Double.parseDouble(jTextField1.getText());
        Calculation = 3;
        jTextField1.setText("");
        jLabel1.setText(num + "*");
    }//GEN-LAST:event_Boton_MultiplicacionActionPerformed

    private void Boton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BorrarActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_Boton_BorrarActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        disable(); //Llama al metodo disable, se apaga.
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        enable(); //LLama al metodo enable, se enciede.
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void Boton_noseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_noseActionPerformed

        int length = jTextField1.getText().length();
        int number = jTextField1.getText().length() - 1;
        String store;

        if (length > 0) {

            StringBuilder Back = new StringBuilder(jTextField1.getText());
            Back.deleteCharAt(number);
            store = Back.toString();
            jTextField1.setText(store);

        }


    }//GEN-LAST:event_Boton_noseActionPerformed

    private void Boton_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SumaActionPerformed
        num = Double.parseDouble(jTextField1.getText());
        Calculation = 1;
        jTextField1.setText("");
        jLabel1.setText(num + "+");


    }//GEN-LAST:event_Boton_SumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_0;
    private javax.swing.JButton Boton_1;
    private javax.swing.JButton Boton_2;
    private javax.swing.JButton Boton_3;
    private javax.swing.JButton Boton_4;
    private javax.swing.JButton Boton_5;
    private javax.swing.JButton Boton_6;
    private javax.swing.JButton Boton_7;
    private javax.swing.JButton Boton_8;
    private javax.swing.JButton Boton_9;
    private javax.swing.JButton Boton_Borrar;
    private javax.swing.JButton Boton_Division;
    private javax.swing.JButton Boton_Igual;
    private javax.swing.JButton Boton_Multiplicacion;
    private javax.swing.JButton Boton_Punto;
    private javax.swing.JButton Boton_Resta;
    private javax.swing.JButton Boton_Suma;
    private javax.swing.JButton Boton_nose;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
